\c d7d1gds47dr9oa

INSERT INTO amenities_amenity (name, image) VALUES
('Heating', 'https://www.reshot.com/preview-assets/icons/VJLXFPZWAB/water-heating-VJLXFPZWAB.svg'),
('Air Conditioning', 'https://www.reshot.com/preview-assets/icons/5MUHFP6QBZ/air-conditioning-5MUHFP6QBZ.svg'),
('WiFi', 'https://www.reshot.com/preview-assets/icons/DQZC9PBJME/wifi-DQZC9PBJME.svg'),
('Parking', 'https://www.reshot.com/preview-assets/icons/YW4CGQ8JEV/parking-YW4CGQ8JEV.svg'),
('Gym', 'https://www.reshot.com/preview-assets/icons/WS79HTVFXE/gym-dumbbell-WS79HTVFXE.svg'),
('Pool', 'https://www.reshot.com/preview-assets/icons/RMA9GY5SEX/swimming-pool-RMA9GY5SEX.svg'),
('Hot Tub', 'https://www.reshot.com/preview-assets/icons/5EPTZWL79S/hot-tub-5EPTZWL79S.svg'),
('Kitchen', 'https://www.reshot.com/preview-assets/icons/YF9WTCLDKV/kitchen-sink-YF9WTCLDKV.svg'),
('Dishes and Silverware', 'https://www.reshot.com/preview-assets/icons/TBDKN36ULZ/dishes-TBDKN36ULZ.svg'),
('Dishwasher', 'https://www.reshot.com/preview-assets/icons/Q3YBKWC2TU/clean-dishes-Q3YBKWC2TU.svg'),
('TV', 'https://www.reshot.com/preview-assets/icons/ZRPASWEJTX/tv-ZRPASWEJTX.svg'),
('Board Games', 'https://www.reshot.com/preview-assets/icons/3SRUDQLYH5/board-game-3SRUDQLYH5.svg'),
('Patio', 'https://www.reshot.com/preview-assets/icons/7WMD2JRUPE/deck-chair-7WMD2JRUPE.svg'),
('Backyard', 'https://www.reshot.com/preview-assets/icons/LK3RW8HNJZ/tree-LK3RW8HNJZ.svg'),
('Washer and Dryer', 'https://www.reshot.com/preview-assets/icons/5E6SCBK2HW/washer-machine-5E6SCBK2HW.svg'),
('Iron', 'https://www.reshot.com/preview-assets/icons/V8S5HG9YE2/ironing-clothes-V8S5HG9YE2.svg'),
('Hair Dryer', 'https://www.reshot.com/preview-assets/icons/FBW8GZ26NS/hair-dryer-FBW8GZ26NS.svg'),
('Shampoo', 'https://www.reshot.com/preview-assets/icons/D9EJMRAVTS/shampoo-D9EJMRAVTS.svg'),
('Conditioner', 'https://www.reshot.com/preview-assets/icons/8M96ST4VA5/shampoo-8M96ST4VA5.svg'),
('Bathtub', 'https://www.reshot.com/preview-assets/icons/SWRXC3L48F/clean-bathtub-SWRXC3L48F.svg'),
('Smoke Alarm', 'https://www.reshot.com/preview-assets/icons/YJETM7HGRF/smoke-detector-YJETM7HGRF.svg'),
('Self check-in', 'https://www.reshot.com/preview-assets/icons/28QDAR4CPV/check-in-28QDAR4CPV.svg');