# Generated by Django 5.1.3 on 2024-11-16 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('https://www.reshot.com/preview-assets/icons/VJLXFPZWAB/water-heating-VJLXFPZWAB.svg', 'Heating'), ('https://www.reshot.com/preview-assets/icons/5MUHFP6QBZ/air-conditioning-5MUHFP6QBZ.svg', 'Air Conditioning'), ('https://www.reshot.com/preview-assets/icons/DQZC9PBJME/wifi-DQZC9PBJME.svg', 'WiFi'), ('https://www.reshot.com/preview-assets/icons/YW4CGQ8JEV/parking-YW4CGQ8JEV.svg', 'Parking'), ('https://www.reshot.com/preview-assets/icons/WS79HTVFXE/gym-dumbbell-WS79HTVFXE.svg', 'Gym'), ('https://www.reshot.com/preview-assets/icons/RMA9GY5SEX/swimming-pool-RMA9GY5SEX.svg', 'Pool'), ('https://www.reshot.com/preview-assets/icons/5EPTZWL79S/hot-tub-5EPTZWL79S.svg', 'Hot Tub'), ('https://www.reshot.com/preview-assets/icons/YF9WTCLDKV/kitchen-sink-YF9WTCLDKV.svg', 'Kitchen'), ('https://www.reshot.com/preview-assets/icons/TBDKN36ULZ/dishes-TBDKN36ULZ.svg', 'Dishes and Silverware'), ('https://www.reshot.com/preview-assets/icons/Q3YBKWC2TU/clean-dishes-Q3YBKWC2TU.svg', 'Dishwasher'), ('https://www.reshot.com/preview-assets/icons/ZRPASWEJTX/tv-ZRPASWEJTX.svg', 'TV'), ('https://www.reshot.com/preview-assets/icons/3SRUDQLYH5/board-game-3SRUDQLYH5.svg', 'Board Games'), ('https://www.reshot.com/preview-assets/icons/7WMD2JRUPE/deck-chair-7WMD2JRUPE.svg', 'Patio'), ('https://www.reshot.com/preview-assets/icons/LK3RW8HNJZ/tree-LK3RW8HNJZ.svg', 'Backyard'), ('https://www.reshot.com/preview-assets/icons/5E6SCBK2HW/washer-machine-5E6SCBK2HW.svg', 'Washer and Dryer'), ('https://www.reshot.com/preview-assets/icons/V8S5HG9YE2/ironing-clothes-V8S5HG9YE2.svg', 'Iron'), ('https://www.reshot.com/preview-assets/icons/FBW8GZ26NS/hair-dryer-FBW8GZ26NS.svg', 'Hair Dryer'), ('https://www.reshot.com/preview-assets/icons/D9EJMRAVTS/shampoo-D9EJMRAVTS.svg', 'Shampoo'), ('https://www.reshot.com/preview-assets/icons/8M96ST4VA5/shampoo-8M96ST4VA5.svg', 'Conditioner'), ('https://www.reshot.com/preview-assets/icons/SWRXC3L48F/clean-bathtub-SWRXC3L48F.svg', 'Bathtub'), ('https://www.reshot.com/preview-assets/icons/YJETM7HGRF/smoke-detector-YJETM7HGRF.svg', 'Smoke Alarm'), ('https://www.reshot.com/preview-assets/icons/28QDAR4CPV/check-in-28QDAR4CPV.svg', 'Self check-in')], max_length=90), blank=True, size=None),
        ),
    ]
