# Generated by Django 5.1.3 on 2024-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('properties', '0003_remove_property_photos_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AlterField(
            model_name='property',
            name='cancellation_policy',
            field=models.CharField(choices=[('Flexible', 'Receive a full refund if canceled at least 24 hours before check-in; after that, no refund.'), ('Moderate', 'Receive a full refund if canceled at least 5 days before check-in; first night non-refundable after that.'), ('Strict', 'Receive half a refund if canceled at least 14 days before check-in; no refund after that.'), ('Long-Term', 'Receive a full refund if canceled at least 30 days before check-in; no refund after that.'), ('Super Strict 30 Days', 'You will receive half a refund if canceled at least 30 days before check-in; no refund after that.'), ('Super Strict 60 Days', 'You will receive half a refund if canceled at least 60 days before check-in; no refund after that.'), ('Non-Refundable', 'No refund if canceled at any time.')], default=('Flexible', 'Receive a full refund if canceled at least 24 hours before check-in; after that, no refund.'), max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='amenities.amenity'),
        ),
    ]
