# Generated by Django 5.1.3 on 2024-11-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_address_address_string_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_string',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.IntegerField(default=0),
        ),
    ]
